### ISSUE TITLE
Add Conda Package

### ISSUE THREAD

**Issue by MarcSkovMadsen** [awesome-panel/awesome-panel-cli#2]
Make a conda package available on `conda-forge`.

Inspiration might be found in the [panel-chemistry](https://github.com/awesome-panel/panel-chemistry) repository which is already on `conda-forge`.

## Tasks

- [] Create conda-forge recipe
- [] Publish the package (manually)
- [] Document conda package in README
- [] Document conda package in Docs
- [] Setup automated build and release in via github actions
